// This code was generated by a kontent-generators-net tool 
// (see https://github.com/Kentico/kontent-generators-net).
// 
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated. 
// For further modifications of the class, create a separate file with the partial class.

using System;
using System.Collections.Generic;
using Kentico.Kontent.Delivery.Abstractions;

namespace KenticoKontentModels
{
    public partial class FoodMenu
    {
        public const string Codename = "menu";
        public const string MenuItemsCodename = "menu_items";
        public const string NameCodename = "name";
        public const string UntitledUrlSlugCodename = "url";

        public IEnumerable<object> MenuItems { get; set; }
        public string Name { get; set; }
        public ContentItemSystemAttributes System { get; set; }
        public string Url { get; set; }
    }
}