// This code was generated by a kontent-generators-net tool 
// (see https://github.com/Kentico/kontent-generators-net).
// 
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated. 
// For further modifications of the class, create a separate file with the partial class.

using System;
using System.Collections.Generic;
using Kentico.Kontent.Delivery.Abstractions;

namespace KenticoKontentModels
{
    public partial class Home
    {
        public const string Codename = "home";
        public const string ArticlesCodename = "articles";
        public const string ContactCodename = "contact";
        public const string HeroUnitCodename = "hero_unit";
        public const string TitleCodename = "title";
        public const string UrlPatternCodename = "url_pattern";

        public IEnumerable<object> Articles { get; set; }
        public IRichTextContent Contact { get; set; }
        public IEnumerable<object> HeroUnit { get; set; }
        public ContentItemSystemAttributes System { get; set; }
        public string Title { get; set; }
        public string UrlPattern { get; set; }
    }
}